[package]
name = "rp-pio-serial"
authors = ["JimesYang <admin@sndnvaps.com>"]
version = "0.6.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "PIO-based software serial for RP2040 & RP2350 using arbitrary GPIO pins"
documentation = "https://docs.rs/rp-pio-serial"
repository = "https://github.com/sndnvaps/rp-pio-serial"
keywords = [
    "raspberry-pi",
    "rp2350",
    "rp2040",
    "embedded-hal",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]

[package.metadata.docs.rs]
features = [
    "rp2040",
]
targets = ["thumbv6m-none-eabi"]

[features]
default = ["rp2040"]
rp2040 = ["dep:rp2040-hal"]
rp2350 = ["dep:rp235x-hal"]

[lib]
name = "rp_pio_serial"
path = "src/lib.rs"


[dependencies]
rp2040-hal = { version = "0.10.2", features = ["rt"], optional = true }
rp235x-hal = { version = "0.4.0", features = ["rt"], optional = true }
cortex-m = "0.7.7"
embedded-hal = "1.0"
heapless = "0.8"

[target.'thumbv6m-none-eabi'.dependencies]
pio = {version = "0.2.1"}
pio-proc = "0.2.2"

[target.'thumbv8m.main-none-eabihf'.dependencies]
pio = "0.3.0"
pio-core = {version = "0.3.0"}
pio-proc = "0.3.0"


